version: "3.9"

services:
  app:
    build: .
    container_name: lambda
    ports:
      - "8080:8080"
    environment:
      DB_CONNECTION: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: lambda
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DEBUG: "false"
      TZ: Asia/Ulaanbaatar
    depends_on:
      - db
    volumes:
      - ./uploads:/app/public/uploads

volumes:
  postgres-data:
