version: '3.9'
services:
  db:
    image: "postgres:13-alpine"
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lambda
      TZ: Asia/Ulaanbaatar
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      target: dev
    container_name: lambda-dev
    ports:
      - "8080:8080"
    environment:
      DB_CONNECTION: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: lambda
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: BIzaSyBUEDlwdKQ0AZOnHOkZv2MIw0GlRjql6V4
      TZ: Asia/Ulaanbaatar
    depends_on:
      - db
    volumes:
      - ./public/uploaded:/app/public/uploaded
      - ./lambda:/app/lambda

volumes:
  postgres-data:
